import type { ThemeDefinition } from "vuetify";

export const sampleTheme: ThemeDefinition = {
  dark: false,
  colors: {
    background: "#FFFFFF",
    surface: "#FFFFFF",
    primary: "#83c930",
    "primary-darken-1": "#FF5947",
    "primary-lighten-1": "#E1675A",
    "primary-lighten-2": "#88ac4c",
    secondary: "#40455F",
    "laravel-dark": "#252a37",
    "secondary-lighten-1": "#6e6d71",
    "secondary-darken-1": "#252a37",
    "secondary-lighten-2": "#bcbec0",
    "secondary-lighten-3": "#e6e7e8",
    error: "#EB4432",
    info: "#2196F3",
    success: "#4CAF50",
    warning: "#FB8C00",
    accent: "#f17030",
    purple: "#5a286c",
    cyan: "#16bdcf",
    "on-primary": "#FFFFFF",
    "on-info": "#FFFFFF",
    "on-error": "#FFFFFF",
    "on-success": "#FFFFFF",
    "on-warning": "#FFFFFF",
    "on-accent": "#FFFFFF",
    "on-purple": "#FFFFFF",
    "on-cyan": "#FFFFFF",
  },
};
